name: FastAPI + Github Action

on: [push]

jobs:
  build:
  
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
    - name: Create and activate virtual env
      run: |
        python3 -m venv venv && . venv/bin/activate
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    - name: Run application
      run: |
        uvicorn main:app --port=8081
    
